home/urls.py
from django.conf.urls import url

from home import views

urlpatterns=[

    url("^$",views.indexview.as_view(),name="index"),
    url("^index/",views.indexview.as_view(),name="index"),
    url("^create/",views.create,name='create')
]

shop/urls.py
from django.conf.urls import url

from shop import views

urlpatterns=[
    url(r"shop/(?P<productid>\d+)/$",views.shop,name='shop')
]

shopcart/urls.py
from django.conf.urls import url

from shopcart import views

urlpatterns=[
    url(r'shopcart/$',views.shopcart,name='shopcart'),
    url(r'shopcart/address/',views.shopaddress,name='address')
]

user/urls.py
from django.conf.urls import url

from user import views

urlpatterns=[
    url(r'login/',views.login,name="login"),
    url(r'logout/',views.logout,name='logout'),
    url(r'register/',views.register,name='register'),
    url(r'imgcode/',views.imgcode,name='imgcode'),
    url(r'sendmsg/',views.sendmsg,name='sendmsg'),
    url(r'verifyphone/',views.verifyphone,name='verifyphone'),
    url(r'pay/',views.pay,name='pay')
]

yiban0/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("home.urls",namespace='home')),
    url(r'^', include("user.urls",namespace='user')),
    url(r'^',include("shop.urls",namespace='shop')),
    url(r'^',include("shopcart.urls",namespace='shopcart')),
    url(r'^', include("order.urls", namespace='order'))

]

shop/models.py
from django.db import models

# Create your models here.

shopcart/models.py
from django.db import models

# Create your models here.

shop/views.py
import json

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

# Create your views here.
from django_redis import get_redis_connection

from home.models import YibanDiscountProduct, YibanSku
from user.models import YibanUser


def shop(request,productid):
    if request.method=='GET':
        user1 = None
        cart = request.COOKIES.get('cart', {})
        if cart :
            cart=json.loads(cart)
        carttotal = sum(cart.values())
        if request.session.get('id'):
            uid = request.session.get('id')
            user1 = YibanUser.objects.get(id=uid)
            redis_cli=get_redis_connection('cart')
            redis_json_data=redis_cli.get(f'redis_data_{uid}') if redis_cli.get(f'redis_data_{uid}') else '{}'
            redis_data = json.loads(redis_json_data)
            carttotal=sum(redis_data.values())
        try:
            product=YibanDiscountProduct.objects.get(id=productid)
            print(product)
            productimgs=product.productimg.split(';')
            print(productimgs)

            skudict=json.loads(product.skudict)
            colors=skudict.get('color')
            sizes=skudict.get('size')
            skus=product.skus.all()
            store=sum([sku.inventory for sku in skus])
        except:
            return HttpResponse('this product do not exist!')
        context={
            'product':product,
            'colors':colors,
            'sizes':sizes,
            'store':store,
            "productimgs":productimgs,
            'user1':user1,
            'skus':skus,
            'carttotal':carttotal
        }
        return render(request,'Shop.html',context=context)
    if request.method=='POST':
        user1=None
        if request.session.get('id'):
            uid = request.session.get('id')
            user1 = YibanUser.objects.get(id=uid)
        skupro=request.POST.get('skupro')
        skuprodict=json.dumps({'color':skupro.split(';')[0],'size':skupro.split(';')[1]})
        print(skuprodict)
        skuid=YibanSku.objects.filter(skuprops=skuprodict)[0].id
        num = request.POST.get('num')
        print(num)

        if not user1:
            cart = request.COOKIES.get('cart', {})
            if cart:
                cart = json.loads(cart)
            print(cart)
            cart[str(skuid)] = cart.get(str(skuid), 0) + int(num)
            carttotal = sum(cart.values())
            cartjson = json.dumps(cart)
            res=JsonResponse({'code': 'ok', 'msg': carttotal})
            res.set_cookie('cart',cartjson)
            return res
        else:
            redis_cli=get_redis_connection('cart')
            json_redis_data = redis_cli.get(f'redis_data_{uid}') if redis_cli.get(f'redis_data_{uid}') else '{}'
            print(json_redis_data)
            redis_data=json.loads(json_redis_data)
            if num:
                redis_data[str(skuid)] = redis_data.get(str(skuid), 0) + int(num)
            else:
                redis_data.pop(str(skuid))
            carttotal=sum(redis_data.values())
            json_redis_data=json.dumps(redis_data)
            redis_cli.set(f'redis_data_{uid}',json_redis_data)
            return JsonResponse({'code':'ok','msg':carttotal})

shopcart/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django_redis import get_redis_connection

from home.models import YibanSku
from user.models import YibanUser


def shopcart(request):
    if request.method=='GET':
        user1=None
        if request.session.get('id'):
            uid=request.session.get('id')
            user1=YibanUser.objects.get(id=uid)
            redis_cli = get_redis_connection('cart')
            redis_json_data = redis_cli.get(f'redis_data_{uid}') if redis_cli.get(f'redis_data_{uid}') else '{}'
            redis_data = json.loads(redis_json_data)
            carttotal = sum(redis_data.values())
            skudicts = {}
            for skuid, num in redis_data.items():
                try:
                    sku = YibanSku.objects.get(id=int(skuid))
                    skudicts[sku] = num

                except Exception as e:
                    return HttpResponse(str(e))
            context = {
                'user1': user1,
                'skudicts': skudicts,
                'carttotal': carttotal
            }
            return render(request, 'SHOP_Cart.html', context)

        else:
            pass


    if request.method=='POST':
        return HttpResponse('ok')


def shopaddress(request):
    user1=None
    if request.session.get('id'):
        uid=request.session.get('id')
        user1=YibanUser.objects.get(id=uid)
    context={
        'user1':user1
    }
    return render(request,'shopaddress.html',context)

templates/SHOP_Cart.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link href="/static/css/shoppingCart.css" type="text/css" rel="stylesheet" />
		<style>
			@font-face {
			  font-family: 'iconfont';
			  src: url('/static/iconfont.eot'); /* IE9*/
			  src: url('/static/iconfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
			  url('/static/iconfont.woff') format('woff'), /* chrome、firefox */
			  url('/static/iconfont.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
			  url('/static/iconfont.svg#iconfont') format('svg'); /* iOS 4.1- */
			}
			.I-ico{
			    font-family:"iconfont" !important;
			    font-size:16px;font-style:normal;
			    -webkit-font-smoothing: antialiased;
			    -webkit-text-stroke-width: 0.2px;
			    -moz-osx-font-smoothing: grayscale;		    
			 }
			*{margin: 0px; padding: 0px;}
			body,html{font-size: 12px; margin: 0 auto;}
			body{width: 1263px; height:auto;}
			a{text-decoration: none;}
			li{list-style-type: none;}
			/*头部（g-hd）部分*/
			#j_topbar{width: 1263px; height:30px;background: #F9F9F9;}
			#j_topbar .g-top{width: 1190px; line-height: 30px; margin: 0px 36.5px;}
			.g-topL{width: 191px; height: 30px; float: left;}
			.indexs,.land,.register{color: #666}
			.g-topR{width: 404px; height: 30px; float: right;}
			.g-topR a{ color: #666;}
			.g-topR i{font-style: normal; color: #ddd;}
			.hd{width: 1263px; height: 138px; background: #fff;}
			.top{width: 1190px; height: 60px; margin: 0px 36.5px; padding:20px 0px ;}
			.top .logo{float: left;}
			.top .top-sch{width: 350px; height: 60px; float: right;}
			.top .top-sch .form-box{border: 2px solid #f10582;}
			.top .top-sch .form-box .u-sch-text{width: 246px; height: 24px; padding: 5px 0px; margin-left: 20px; border: 0px;outline:none}
			.top .top-sch .form-box .u-sch-btn{width: 74px;height: 34px; background:#f10582 ; color: white; border:0px ; float: right;}
			.top .top-sch .sch-keywords{margin-top: 10px; width: 350px; height: 18px;}
			.top .top-sch .sch-keywords span,a {color: #999;}
			.hd .shop_m-nav{width: 1263px; height: 36px; background: #EB2323;}
			.hd .shop_m-nav .top_nav{width: 1190px; height: 36px; display: block; margin: 0 auto;}
			.hd .shop_m-nav .top_nav li a{color: white; font-size:14px; font-weight:500;float: left; display: inline-block; width: 99px;line-height: 36px; text-align: center;}
			.hd .shop_m-nav .top_nav li a:hover{background: #db0a76;}
		</style>
		<script src="/static/js/jquery-1.12.3.js"></script>
		<script src="/static/js/jquery.cookie.js"></script>
{#		<script src="/static/js/shops_cart.js"></script>#}
	</head>
	<body>
		<div class="g-hd">
			<!--头部公共部分-->
            <div id="j_topbar" class="m-topbar f-cb">
            	<div class="g-top">
            		<div class="g-topL">
	            		<a href="/index/" class="indexs">
	            			<span class="I-ico" style="color: #f10582;">&#xe73d;</span> 衣扮网首页	
	            		</a>
	            		{% if user1 %}
                            <span id="user">{{ user1.username }}</span>
                        <a href="{%url 'user:logout' %}" class="land">
	            			[注销]
	            		</a>

                        {% else %}
	            		<a href="{%url 'user:login' %}" class="land">
	            			[登录]
	            		</a>
	            		<a href="{% url 'user:register' %}" class="register">
	            			[免费注册]
	            		</a>
                        {% endif %}
            		</div>          	            		
            		<div class="g-topR">
            			<a href="#" target="_blank" style="color: #f10582;">下载app&nbsp;</a>
            			<a href="#" target="_blank">我的订单</a> <i>|</i>
            			<a href="#" target="_blank"> 
            				<span class="I-ico" style="color: #f10582;">&#xe95f;</span>购物车<span id="cartnumtotal">{{ carttotal }}</span>件
            			</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico"style="color: gold;">&#xeaaa;</span>收藏夹
            			</a> <i>|</i>
            			<a href="#" target="_blank">互联支付</a> <i>|</i>
            			<a href="#" target="_blank">帮助中心</a>
            		</div>
            	</div>
            </div>           
            <div class="hd">
            	<!--搜索栏-->
            	<div class="top">
            		<div class="logo"><a href="/index/" target="_blank"><img src="/static/img/imgs/logo.png"/></a></div>
            		<div class="top-sch">
            			<div class="form-box">
            				<form style="position: relative;">
            					<span class="I-ico" style="position: absolute; top: 10px; left: 5px;">&#xe679;</span>
            					<input type="text" class="u-sch-text" placeholder="请输入您要搜的商品关键字！"/>
            					<input type="submit" class="u-sch-btn" value="搜 索" />
            				</form>
            			</div>
            			<div class="sch-keywords">
            				<span >热门搜索：</span>
            				<a href="#">连衣裙&nbsp;</a>
            				<a href="#">T桖&nbsp;</a>
            				<a href="#">POLO衫&nbsp;</a>
            				<a href="#">短裙&nbsp;</a>
            				<a href="#">半短裙&nbsp;</a>
            			</div>
            		</div>
            	</div>
            	<div class="shop_m-nav">
            		<ul class="top_nav">
            			<li><a href="/index/">首页</a></li>
            			<li><a href="">女装特卖</a></li>
            			<li><a href="">男装特卖</a></li>
            			<li><a href="">童装特卖</a></li>
            			<li><a href="">内衣特卖</a></li>
            			<li><a href=""><span class="I-ico">&#xe6e0;</span> 限时特卖</a></li>
            			<li><a href="">明星穿搭秘籍</a></li>
            			<li><a href="">美衣盒子</a><img style="position: absolute; left: 800px; top: 120px;" src="/static/img/imgs/hot.gif"/></li>
            		</ul>           		
            	</div>
            </div>	
        </div>
        <div id="my-shopping-cart">
			<div class="cart-text">
				<h1>我的购物车</h1>
				<p>查看购物车商品清单，增加减少商品数量，并勾选想要的商品进入下一步操作。</p>
			</div>
			<div id="shopCar" class="shoppping-cart-content">
				<table>
					<thead>
						<tr class="shoppping-cart-content-head">
							<td class="w80">序号(商品ID)</td>
							<td class="w560">商品</td>
							<td class="w80">单价(元)</td>
							<td class="w120">数量</td>
							<td class="w80">小计(元)</td>
							<td class="w80">操作</td>
						</tr>
					</thead>
					<tbody>
						<th class="shoppping-cart-content-title" colspan="6">
							<div class="store-title">序号:</div>
							<div class="store-activity"><a href="">店铺活动，满29免运费</a></div>
						</th>

                        {% for sku,num in skudicts.items %}
                             <tr class="trnum">
                                <td>{{ sku.id }}</td>
                                <td>{{ sku.product.longname }}
                                    <span class="skuprops">{{sku.skuprops }}</span>
                                </td>
                                <td style="color:deeppink">￥{{ sku.primaryprice }}</td>
                                <td >{{ num }}</td>
                                <td class="skutotal"></td>
                                <td><button class="del">删除</button></td>
                                <td>
                                <button class="plus">+</button>
                                <button class="minus">-</button>
                                </td>
                             </tr>
                        {% endfor %}


					</tbody>
					<tfoot>
						<th class="tstore-totle-money" colspan="6">
							<div class="TTM-text">商品合计:</div>
							<div class="TTM-all-money"><span id="TTM-all-money"></span>元</div>
						</th>
					</tfoot> 
	
				</table>
					
				<div class="totle-money-text">商品总价(不含运费) <span id="totalPrice"></span>元</div>
				<div class="next-step">
					<div class="next-step-tetx">
						<a href="/shopcart/address/">
							<div class="NST-bg"><img src="/static/img/imgs/next.jpg"/></div>
							<span>下一步，填写核对购物信息</span>
						</a>
					</div>
	
				</div>
				<div class="gest-you-like">猜您喜欢的宝贝</div>
				<div class="show-you"></div>								
			</div>
	</div>

	</body>
<script>
    function computetotal(){
        var numtotal=0;
        var tmtotal=0;
        $.each($('.skutotal'),function(i,obj){
           var skuprimaryprice=parseFloat($(this).siblings().eq(2).html().slice(1,))
           var skunum=parseInt($(this).siblings().eq(3).html())
            numtotal+=skunum
           skutotal=skuprimaryprice*skunum
           $(this).html(skutotal)
           tmtotal+=skutotal
            console.log(tmtotal)
           $('#TTM-all-money').html(tmtotal)
           $('#totalPrice').html(tmtotal)
       })
        $('#cartnumtotal').html(numtotal)
    }
    $(function () {
           $.each($('.skuprops'),function (i,obj) {
               var skuprops=JSON.parse(obj.innerHTML)
               obj.innerHTML='  颜色:'+'<span class="skucolor">'+skuprops.color+'</span>'+' 尺寸:'+'<span class="skusize">'+skuprops.size+'</span>'

           })
       computetotal()
        $('.plus').click(function () {
            var skunum=parseInt($(this).parent().siblings().eq(3).html())
            num=skunum+1
            $(this).parent().siblings().eq(3).html(num)
            computetotal()
            var skucolor=$(this).parent().parent().find('.skucolor').html()
            var skusize=$(this).parent().parent().find('.skusize').html()
            var skupro=skucolor+';'+skusize
            console.log(skupro)


            $.ajax({
                url:'/shop/58/',
                data: {'skupro': skupro,'num':1},
                dataType: 'json',
                type: 'post',
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                success:function(data){
                       console.log(data)
                }
            })

        })
        $('.minus').click(function () {
            var skunum=parseInt($(this).parent().siblings().eq(3).html())
            num=skunum-1
            $(this).parent().siblings().eq(3).html(skunum-1)
            computetotal()
            var skucolor=$(this).parent().parent().find('.skucolor').html()
            var skusize=$(this).parent().parent().find('.skusize').html()
            var skupro=skucolor+';'+skusize

            $.ajax({
                url:'/shop/58/',
                data: {'skupro': skupro,'num':-1},
                dataType: 'json',
                type: 'post',
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                success:function(data){
                       console.log(data)
                }
            })

        })
        $('.del').click(function () {
            if(!confirm('确定删除吗？')){
                return
            }
            var skucolor=$(this).parent().parent().find('.skucolor').html()
            var skusize=$(this).parent().parent().find('.skusize').html()
            var skupro=skucolor+';'+skusize

            $.ajax({
                url:'/shop/58/',
                data: {'skupro': skupro,'num':null},
                dataType: 'json',
                type: 'post',
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                success:function(data){
                       console.log(data)
                }
            })
            $(this).parent().parent().remove()


        })

    })
</script>
</html>

templates/shopaddress.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<link href="/static/css/shoppingCart.css" type="text/css" rel="stylesheet" />
		<style>
			@font-face {
			  font-family: 'iconfont';
			  src: url('/static/iconfont.eot'); /* IE9*/
			  src: url('/static/iconfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
			  url('/static/iconfont.woff') format('woff'), /* chrome、firefox */
			  url('/static/iconfont.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
			  url('/static/iconfont.svg#iconfont') format('svg'); /* iOS 4.1- */
			}
			.I-ico{
			    font-family:"iconfont" !important;
			    font-size:16px;font-style:normal;
			    -webkit-font-smoothing: antialiased;
			    -webkit-text-stroke-width: 0.2px;
			    -moz-osx-font-smoothing: grayscale;
			 }
			*{margin: 0px; padding: 0px;}
			body,html{font-size: 12px; margin: 0 auto;}
			body{width: 1263px; height:auto;}
			a{text-decoration: none;}
			li{list-style-type: none;}
			/*头部（g-hd）部分*/
			#j_topbar{width: 1263px; height:30px;background: #F9F9F9;}
			#j_topbar .g-top{width: 1190px; line-height: 30px; margin: 0px 36.5px;}
			.g-topL{width: 191px; height: 30px; float: left;}
			.indexs,.land,.register{color: #666}
			.g-topR{width: 404px; height: 30px; float: right;}
			.g-topR a{ color: #666;}
			.g-topR i{font-style: normal; color: #ddd;}
			.hd{width: 1263px; height: 138px; background: #fff;}
			.top{width: 1190px; height: 60px; margin: 0px 36.5px; padding:20px 0px ;}
			.top .logo{float: left;}
			.top .top-sch{width: 350px; height: 60px; float: right;}
			.top .top-sch .form-box{border: 2px solid #f10582;}
			.top .top-sch .form-box .u-sch-text{width: 246px; height: 24px; padding: 5px 0px; margin-left: 20px; border: 0px;outline:none}
			.top .top-sch .form-box .u-sch-btn{width: 74px;height: 34px; background:#f10582 ; color: white; border:0px ; float: right;}
			.top .top-sch .sch-keywords{margin-top: 10px; width: 350px; height: 18px;}
			.top .top-sch .sch-keywords span,a {color: #999;}
			.hd .shop_m-nav{width: 1263px; height: 36px; background: #EB2323;}
			.hd .shop_m-nav .top_nav{width: 1190px; height: 36px; display: block; margin: 0 auto;}
			.hd .shop_m-nav .top_nav li a{color: white; font-size:14px; font-weight:500;float: left; display: inline-block; width: 99px;line-height: 36px; text-align: center;}
			.hd .shop_m-nav .top_nav li a:hover{background: #db0a76;}
		</style>
		<script src="/static/js/jquery-1.12.3.js"></script>
		<script src="/static/js/jquery.cookie.js"></script>
	</head>
	<body>
		<div class="g-hd">
			<!--头部公共部分-->
            <div id="j_topbar" class="m-topbar f-cb">
            	<div class="g-top">
            		<div class="g-topL">
	            		<a href="/index/" class="indexs">
	            			<span class="I-ico" style="color: #f10582;">&#xe73d;</span> 衣扮网首页
	            		</a>
	            		{% if user1 %}
                            <span id="user">{{ user1.username }}</span>
                        <a href="{%url 'user:logout' %}" class="land">
	            			[注销]
	            		</a>

                        {% else %}
	            		<a href="{%url 'user:login' %}" class="land">
	            			[登录]
	            		</a>
	            		<a href="{% url 'user:register' %}" class="register">
	            			[免费注册]
	            		</a>
                        {% endif %}
            		</div>
            		<div class="g-topR">
            			<a href="#" target="_blank" style="color: #f10582;">下载app&nbsp;</a>
            			<a href="#" target="_blank">我的订单</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico" style="color: #f10582;">&#xe95f;</span>购物车<span id="cartnumtotal">{{ carttotal }}</span>件
            			</a> <i>|</i>
            			<a href="#" target="_blank">
            				<span class="I-ico"style="color: gold;">&#xeaaa;</span>收藏夹
            			</a> <i>|</i>
            			<a href="#" target="_blank">互联支付</a> <i>|</i>
            			<a href="#" target="_blank">帮助中心</a>
            		</div>
            	</div>
            </div>
            <div class="hd">
            	<!--搜索栏-->
            	<div class="top">
            		<div class="logo"><a href="/index/" target="_blank"><img src="/static/img/imgs/logo.png"/></a></div>
            		<div class="top-sch">
            			<div class="form-box">
            				<form style="position: relative;">
            					<span class="I-ico" style="position: absolute; top: 10px; left: 5px;">&#xe679;</span>
            					<input type="text" class="u-sch-text" placeholder="请输入您要搜的商品关键字！"/>
            					<input type="submit" class="u-sch-btn" value="搜 索" />
            				</form>
            			</div>
            			<div class="sch-keywords">
            				<span >热门搜索：</span>
            				<a href="#">连衣裙&nbsp;</a>
            				<a href="#">T桖&nbsp;</a>
            				<a href="#">POLO衫&nbsp;</a>
            				<a href="#">短裙&nbsp;</a>
            				<a href="#">半短裙&nbsp;</a>
            			</div>
            		</div>
            	</div>
            	<div class="shop_m-nav">
            		<ul class="top_nav">
            			<li><a href="/index/">首页</a></li>
            			<li><a href="">女装特卖</a></li>
            			<li><a href="">男装特卖</a></li>
            			<li><a href="">童装特卖</a></li>
            			<li><a href="">内衣特卖</a></li>
            			<li><a href=""><span class="I-ico">&#xe6e0;</span> 限时特卖</a></li>
            			<li><a href="">明星穿搭秘籍</a></li>
            			<li><a href="">美衣盒子</a><img style="position: absolute; left: 800px; top: 120px;" src="/static/img/imgs/hot.gif"/></li>
            		</ul>
            	</div>
            </div>
        </div>
        <div id="my-shopping-cart">
			<div class="cart-text">
				<h1>我的地址库</h1>
				<p>选中一个地址，下一步订单支付</p>
			</div>
			<div id="shopCar" class="shoppping-cart-content">
				<table>
					<thead>
						<tr class="shoppping-cart-content-head">
							<td class="w80">序号(地址ID)</td>
							<td class="w560">详细地址</td>
							<td class="w80">姓名</td>
							<td class="w120">电话</td>
							<td class="w80">邮编</td>
							<td class="w80">操作</td>
						</tr>
					</thead>
					<tbody>
						<th class="shoppping-cart-content-title" colspan="6">
							<div class="store-title"></div>
							<div class="store-activity"><a href=""></a></div>
						</th>


                             <tr class="trnum">
                                <td id="userid">{{ user1.id }}</td>
                                <td><input type="text" id='address' value="{{ user1.address }}">

                                </td>
                                <td style="color:deeppink"><input type="text" id="username" value="{{ user1.username }}"></td>
                                <td ><input type="text" id="phone" value="{{ user1.phone }}"></td>
                                <td class="skutotal">518000</td>
                                <td><button class="del">删除</button></td>
                                <td>
                                <button class='modify' >修改</button>

                                </td>
                             </tr>



					</tbody>


				</table>
				<div class="next-step">
					<div class="next-step-tetx">
						<a href="javascript:void(0)">
							<div class="NST-bg"><img src="/static/img/imgs/next.jpg"/></div>
							<span >确认地址并生成订单</span>
						</a>
					</div>

				</div>
				<div class="gest-you-like">猜您喜欢的宝贝</div>
				<div class="show-you"></div>
			</div>
	</div>

	</body>
<script>
$(function () {
    $('.next-step-tetx a').click(function () {
        var address=$('#address').val()
        var phone=$('#phone').val()
        var userid=$('#userid').html()
        var username=$('#username').val()
        $.ajax({
            url:'/order/',
            data:JSON.stringify({'address':address,'phone':phone,'userid':userid,'username':username}),
            dataType:'json',
            type:'put',
            headers: {'X-CSRFToken': '{{ csrf_token }}'},
            success:function(){
                location.href='/order/'
            }
        })

    })

})
</script>
</html>